apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: booksapp
  labels: 
    app: booksapp 
spec: 
  replicas: 1 
  selector: 
    matchLabels: 
      app: booksapp 
  template: 
    metadata: 
      labels: 
        app: booksapp 
    spec: 
      containers: 
      - name: booksapp 
        image: asr2000/bookstoreapp:latest
        ports: 
          - containerPort: 8080
        env:
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom:
              configMapKeyRef:
                name: mongodb-configmap
                key: database_url
