version : "3" 
services: 
  mongodb: 
    image: mongo:latest 
    container_name: "mongodb" 
    ports: 
      - 27017:27017 
  springboot-mongo: 
    image: springapp
    container_name: springboot-mongo
    ports: 
      - 8090:8080 
    links: 
      - mongodb 